version: "3.9"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=calendar
      - POSTGRES_PASSWORD=calendar
      - POSTGRES_DB=calendar
    ports:
     - "5432:5432"
    networks:
      - calendar-net

  calendar:
    image: calendar:latest
    build:
      context:
        hw12_13_14_15_calendar
      dockerfile:
        build/Dockerfile
    ports:
      - "2895:2895"
    networks:
      - calendar-net

networks:
  calendar-net:
